# Generated by Django 5.0.3 on 2024-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0003_book_delete_booking_delete_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
