# Generated by Django 5.0.3 on 2024-03-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0004_book_inventory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='RestaurantA_price_3758c5_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='inventory',
        ),
    ]
