# Generated by Django 5.0.3 on 2024-03-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantApp', '0005_remove_book_restauranta_price_3758c5_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
